title: Yutao Cao | Robotics & AI
description: Master's Student at USC specializing in 3D Perception and Sim-to-Real Robotics
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "air" # Clean, professional white theme

# Site Settings
url: "https://YutaoC24.github.io"
baseurl: "" # Leave empty

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-include-cache  # <--- Add this line